### ISSUE TITLE
IE 9 Support

### ISSUE THREAD

**Issue by mattnowdev** [Zhouzi/GentleForm#7]
Hi, 
Thanks for your great work, i recognize that you using "classList" property in production script. Which IE 9 doesn't support, maybe you can use some script that gonna help like this https://gist.github.com/devongovett/1381839.

**Comment by zhouzi** [comment]
Hey @MateuszNowicki, thanks for the heads up! I'll properly test GentleForm on IE 9 to add the required polyfills. I'll keep this issue updated ;)

**Comment by zhouzi** [comment]
I've released GentleForm v2 which comes with a simpler API and a stronger polyfill for the html5 constraint validation api. I've also added a note regarding [browser support](https://github.com/Zhouzi/GentleForm#browser-support) and classList.

Please note that there are many breaking changes compared to v1, but I have updated the documentation accordingly ;)

**Comment by mattnowdev** [comment]
Thank you for letting me know :)
