### ISSUE TITLE
does not work if checkbox is hidden via css for styling

### ISSUE THREAD

**Issue by badpenguin** [Zhouzi/GentleForm#9]
If i set the checkbox via css with display:none to style it in a fashion way then i get this javascript console when submitting the form:

An invalid form control with name='s2q1' is not focusable.

is it a chrome issue? because the onSubmit event seems not fired at all

**Comment by badpenguin** [comment]
Added novalidate to form tag solved it.

**Comment by zhouzi** [comment]
Glad you could figure it out 👍
